config/routes.rb
WordProblemApp::Application.routes.draw do
  post "answer", to: "wordproblems#answer"
  root to: "wordproblems#ask"

end

app/models/word_problem.rb
class WordProblem
	include ActiveModel::Model
	attr_accessor :question

	PATTERN = /What is (-*\d+) (\s*(plus|minus|multiplied|divided|times|over)\s?b?y? (-*\d+))+/i

	validates :question, format: {with: PATTERN, message: "Wrong format!" }

	# def strip_irrelevant_words(phrase)
 #    words = phrase.split[2..-1]
 #    words[words.length-1].gsub!("?","")
 #    words.map! do |word|
 #      word.downcase
 #    end
 #  end

 #  def convert_to_math_syntax(word_array)
 #    word_array.map! do |word|
 #      if word.match(/-?\d+/)
 #        word.to_f
 #      elsif word == "plus"
 #        word = :+
 #      elsif word == "minus"
 #        word = :-
 #      elsif word == "multiplied" || word == "times"
 #        word = :*
 #      elsif word == "divided" || word == "over"
 #        word = :/
 #      else
 #      end
 #    end

 #    word_array.reject { |word| word == nil}
 #  end

 #  def calculate(math_array)
 #    answer = math_array[0].send(math_array[1],math_array[2])

 #    if math_array.length > 3
 #      if (math_array[1] == :+ || math_array[1] == :-) && (math_array[3] == :* || math_array[3] == :/)
 #        answer = math_array[2].send(math_array[3],math_array[4])
 #        answer = math_array[0].send(math_array[1], answer)
 #      else
 #        answer = answer.send(math_array[3], math_array[4])
 #      end
 #    end
 #    answer
 #  end

  def strip_irrelevant_chars(string)
    string.gsub(/[^\d*+\/-]/, "")
  end

  def convert_string_to_math_sign(string)
    string.gsub("plus","+").gsub("minus","-").
    gsub("divided","/").gsub("over","/").gsub("times","*").
    gsub("multiplied","*")
  end

  def float_fix(string)
    string.gsub(/(\d+)/, '\1.0')
  end

  def answer
    clean_math_expression = strip_irrelevant_chars(convert_string_to_math_sign(question))

    float_math_expression = float_fix(clean_math_expression)

    eval(float_math_expression).to_s(:human)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wordproblems_controller.rb
class WordproblemsController < ApplicationController

  def ask
  end

  def answer
  	@question = WordProblem.new({ question: params[:question]})
    @sound_option = params[:sound]

    respond_to do |format|
      if @question.valid?
        @answer = @question.answer
        format.html {  }
        format.js {  }
      else
        @error_message = @question.errors.messages[:question][0]
        format.html { redirect_to root_url }
        format.js { }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wordproblems_helper.rb
module WordproblemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Holly - Tenth Generation AI Computer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/wordproblems/_answervalue.html.erb
<div class="alert alert-success">
  <h3>Holly: The answer is probably <%= @answer %>.</h3>
</div>

app/views/wordproblems/_validationerrors.html.erb
<div class="alert alert-error">
  <h3>Holly: The damage report machine has been damaged - <%= @error_message %></h3>
</div>

app/views/wordproblems/answer.html.erb
<div class="hero-unit">
<%= render 'answervalue' %>
</div>

app/views/wordproblems/answer.js.erb
var load_spoken_answer = function(input, option) {
  if (option == "off"){

  } else {
    sound = new Audio();
    sound.src = "http://api.voicerss.org/?key=8c7b5d2c851c4691b44dd6d668d707dd&hl=en-gb&src=" + input;
    sound.play();
  }
}

var sound_option = "<%= escape_javascript @sound_option %>";
var error_message = "The damage report machine has been damaged. <%= escape_javascript @error_message %>";
var answer_message = "The answer is probably <%= escape_javascript @answer.to_s %>";

$('#answer').show('blind', 200);
if ('<%= escape_javascript @error_message %>') {
  $('#answer').html("<%= escape_javascript render('validationerrors') %>");
  load_spoken_answer(error_message, sound_option)
} else {
  $('#answer').html("<%= escape_javascript render('answervalue') %>");
  load_spoken_answer(answer_message, sound_option);
}

app/views/wordproblems/ask.html.erb
<!-- Holly UI -->
<div class="holly-ui">

      <h1 class="hollyname"><%= image_tag('HollyText.png')%></h1>

  <h1 class="hollysubtitle">Tenth Generation AI Computer</h1>

  <!-- Input from User -->
  <%= form_tag answer_path, remote: true, :authenticity_token => true,
  class: "form-horizontal" do %>
    <div class="input-append">
      <%= text_field_tag :question, "", :"x-webkit-speech" => "", id: "appendedInputButton", placeholder: "Ask me something..." %>
      <%= submit_tag "Ask Holly", class: "btn btn-primary"  %>
    </div>

    <div class="sound-controls">
    Sound Control:
        <div class="switch" data-on="danger" data-on-label="OFF" data-off="primary" data-off-label="ON">
          <%= check_box_tag :sound, "off", false%>
        </div>

    </div>
  <% end %>

  <!-- Holly Answers -->
  <% if @error_message %>
    <%= render 'validationerrors' %>
  <% end %>
  <div id="answer">
  </div>

</div>

<!-- Instructions/Documentation -->
<div class="instructions">

  <div class="qanswer">
    <h1><i class="icon-question-sign icon-2x"></i> Who is Holly?</h1>
    <p>
    "Holly" is a homage/reference to the "peculiar" AI computer from the show <a href="http://en.wikipedia.org/wiki/Red_Dwarf" target="_blank">"Red Dwarf"</a>. She used to have an IQ of 6000 but it's hard to say what IQ she has now. Holly can be your personal calculator; ask her nicely and she will give you the answer.
    </p>
  </div>


<div class="qanswer">
  <h1><i class="icon-lightbulb icon-2x"></i> How does this work?</h1>
  <p>
  As long as your question starts with "what is" and has the pattern <strong>[number] {operation} [number]</strong> then she'll take care of it.
  </p>

  <p><strong>For example:</strong> <em  class="text-info">What is 70 divided by 10?</em></p>

  <p>Also, any number of additional {operation} [number] pairs may be chained on to the end of the above expression.</p>

  <p><strong>For example:</strong> <em  class="text-info">What is 70 plus 3 multiplied by 10?</em></p>

<div class="operations info-box">
  <h2>Valid operations:</h2>
  <ul class="icons-ul">
    <li><i class="icon-li icon-ok"></i>plus</li>
    <li><i class="icon-li icon-ok"></i>minus</li>
    <li><i class="icon-li icon-ok"></i>multiplied by <em><strong>or</strong></em> times</li>
    <li><i class="icon-li icon-ok"></i>divided by <em><strong>or</strong></em> over</li>
  </ul>
  </div>

  <p class="voice-info info-box">Holly also accepts voice input if you're using Google Chrome! Make sure you have sound on if you want to hear Holly answer your question.</p>
</div>

  <div class="qanswer">
    <h1><i class="icon-group icon-2x"></i> Who built this?</h1>

    <p>This Ruby on Rails application was built by <a href="http://www.aomran.com" target="_blank">Ahmed Omran</a> and <a href="http://www.pfranzini.com" target="_blank">Paula Franzini</a> during <a href="http://www.hackeryou.com" target="_blank">HackerYou's</a> Summer Academy. The program/logic behind Holly was pair programmed using Test Driven Development (TDD). We used a bit of Javascript to make this a "one-page" app but it still works when Javascript is disabled.</p>

    <p>Voice input was trivial to implement because it is provided by the Chrome web browser. Holly is enabled by default to respond with sound, this was accomplished by using the Text-to-speech (TTS) API provided for free by <a href="http://www.voicerss.org/" target="_blank">VoiceRSS</a>.</p>
  </div>

</div>